name: Build Windows Client

on:
  push:
    branches:
      - main  # 监听 main 分支的推送
  pull_request:
    branches:
      - main  # 监听针对 main 分支的拉取请求

jobs:
  build-windows:
    name: Build Windows Client
    runs-on: windows-latest  # 指定 Windows 环境
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 递归获取子模块
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      
      - name: Install dependencies
        run: |
          choco install -y openssl
          choco install -y ninja
          choco install -y llvm
          rustup component add rust-src
          rustup target add x86_64-pc-windows-msvc
        shell: powershell
      
      - name: Build RustDesk
        run: |
          cd app
          cargo build --release --target x86_64-pc-windows-msvc
        shell: powershell
      
      - name: Package artifacts
        run: |
          mkdir dist
          cp target/x86_64-pc-windows-msvc/release/rustdesk.exe dist/
          cp -r target/x86_64-pc-windows-msvc/release/resources dist/
        shell: bash
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: dist/
          retention-days: 7