name: Build Windows Client Only

on:
  push:
    branches:
      - main       # 主分支推送时触发
      - develop    # 开发分支推送时触发（可根据需要添加更多）
    paths-ignore:   # 忽略这些路径的变更（可选）
      - 'docs/**'
      - '*.md'

jobs:
  build-windows:
    runs-on: windows-latest  # 使用 Windows 环境
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
          target: x86_64-pc-windows-msvc  # Windows 64位目标
      
      - name: Build Windows Client
        run: cargo build --release --bin rustdesk  # 只编译客户端二进制
        
      - name: Upload Client Binary
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-windows
          path: target/release/rustdesk.exe
